settings: fix -std=c23 build failure
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

As a result `ell` fails the build as:

    ell/settings.c: In function 'l_settings_get_embedded_value':
    ell/settings.c:1521:24: error: incompatible types when returning type '_Bool' but 'const char *' was expected
     1521 |                 return false;
          |                        ^~~~~

The change uses poiter instead of a bool to return the zero value.