dbus: fix -std=c23 build failure
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

As a result `ell` fails the build as:

    ell/dbus.c:1700:24: error: incompatible types when returning type '_Bool' but 'void *' was expected
     1700 |                 return false;
          |                        ^~~~~