test-rtnl: fix -std=c23 build failure
gcc-15 switched to -std=c23 by default:

    https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=55e3bd376b2214e200fa76d12b67ff259b06c212

As a result `ell` fails the build as:

    unit/test-rtnl.c: In function 'test_run':
    unit/test-rtnl.c:501:24: error:
      passing argument 1 of 'l_idle_oneshot' from incompatible pointer type [-Wincompatible-pointer-types]
      501 |         l_idle_oneshot(test_next, NULL, NULL);
          |                        ^~~~~~~~~
          |                        |
          |                        void (*)(void)